// <auto-generated />
namespace TravelGuideWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class revisedDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(revisedDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202312301339219_revisedDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
